<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-message-plugins</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>message-center-plugin-internal</artifactId>
    <name>message-center-plugin-internal</name>
    <description>站内消息插件</description>

    <dependencies>
        <!-- 插件API -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-plugin-api</artifactId>
        </dependency>

        <!-- Spring Boot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- WebSocket -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-common</artifactId>
        </dependency>
    </dependencies>
</project>