<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-message</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>structure-message-core</artifactId>
    <version>${revision}</version>
    <name>message-center-core</name>
    <description>消息中心核心模块</description>

    <dependencies>
        <!-- 公共模块 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-common</artifactId>
        </dependency>

        <!-- web-restful风格依赖 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-restful-web-starter</artifactId>
        </dependency>

        <!-- MyBatis Plus -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

        <!-- Structure MyBatis Plus Starter -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-mybatis-plus-starter</artifactId>
        </dependency>

        <!-- 数据库驱动 -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <!-- HTTP客户端 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>


        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-tenant-starter</artifactId>
        </dependency>
    </dependencies>
</project>