<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-message</artifactId>
        <version>${revision}</version>
    </parent>

    <packaging>pom</packaging>
    <name>message-center-im-provider</name>
    <artifactId>structure-message-im-provider</artifactId>

    <modules>
        <module>structure-message-im-feishu-provider</module>
        <module>structure-message-im-dingtalk-provider</module>
        <module>structure-message-im-wechatwork-provider</module>
        <module>structure-message-im-netease-provider</module>
    </modules>

</project>
