<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-message-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../structure-message-dependencies/pom.xml</relativePath>
    </parent>

    <name>structure-message-repository-mybatis</name>
    <artifactId>structure-message-repository-mybatis</artifactId>
    <description>消息中心MyBatis仓储模块</description>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-infra</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-mybatis-plus-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-infra-mybatis-plus-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-flyway</artifactId>
        </dependency>
    </dependencies>
</project>