<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-message-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../structure-message-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>structure-message-boot</artifactId>
    <name>structure-message-boot</name>
    <description>消息中心启动模块</description>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-log-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-mybatis-plus-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-restful-web-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-interfaces</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-repository-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-internal</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-email</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-im</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-im-feishu-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-im-dingtalk-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-im-wechatwork-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-im-netease-provider</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-plugin-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-security-jwt-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>message-service</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>