<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
        <relativePath/><!-- lookup parent from repository -->
    </parent>

    <artifactId>structure-message-boot</artifactId>
    <name>message-boot</name>
    <description>消息中心启动模块</description>
    <packaging>jar</packaging>

    <version>${revision}</version>

    <properties>
        <structure.version>1.2.3</structure.version>
        <revision>1.0.1-SNAPSHOT</revision>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>2.7.18</spring-boot.version>
        <structure-message.version>${revision}</structure-message.version>
        <structure-security.version>1.0.3</structure-security.version>
    </properties>

    <dependencies>
        <!-- spring 启动依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- 日志插件依赖 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-log-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-mybatis-plus-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>
        <!-- 核心模块 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-core</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-internal</artifactId>
            <version>${structure-message.version}</version>
        </dependency>
        <!-- 邮件插件模块 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-email</artifactId>
            <version>${structure-message.version}</version>
        </dependency>

        <!-- 短信插件模块 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>message-center-plugin-sms</artifactId>
            <version>${structure-message.version}</version>
        </dependency>

        <!-- 短信提供者模块 -->
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-sms-aliyun-provider</artifactId>
            <version>${structure-message.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-sms-tencent-provider</artifactId>
            <version>${structure-message.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-sms-huawei-provider</artifactId>
            <version>${structure-message.version}</version>
        </dependency>

        <!-- 配置处理器 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-jwt-security-starter</artifactId>
            <version>${structure-security.version}</version>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-boot-parent</artifactId>
                <version>${structure.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-message</artifactId>
                <version>${structure-message.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>