<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-message-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../structure-message-dependencies/pom.xml</relativePath>
    </parent>

    <name>structure-message-domain</name>
    <artifactId>structure-message-domain</artifactId>
    <description>消息中心领域层模块</description>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-message-common</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>